checkpoint_dir: checkpoints
data:
  dev_src: data/cleaned/dev.en
  dev_tgt: data/cleaned/dev.gu
  joint_tokenizer: true
  max_len: 250
  source_lang: en
  target_lang: gu
  test_src: data/cleaned/test.en
  test_tgt: data/cleaned/test.gu
  tokenizer_dir: data/tokenized_gu
  train_src: data/cleaned/train.en
  train_tgt: data/cleaned/train.gu
log_dir: logs
model:
  d_model: 512
  dim_feedforward: 2048
  dropout: 0.1
  nhead: 8
  num_decoder_layers: 6
  num_encoder_layers: 6
training:
  batch_size: 16
  clip_grad: 1.0
  eval_every: 1
  label_smoothing: 0.1
  lr: 5e-4
  num_epochs: 10
  warmup_steps: 400
